/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sqdgxhcokvdo3dv6zu6rnluiyq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ianqqxh2zben7ma3vturae5ngy",
    "aws_cognito_identity_pool_id": "us-east-1:c85e0168-2fc0-4b19-8c76-6abee09fcf74",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3EvLLiglF",
    "aws_user_pools_web_client_id": "7sptbqe566fl70r38si12110o4",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "myproject-20230427143504-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://myproject-20230427143504-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
